<?xml version="1.0" encoding="utf-8"?><Database Name="QL_KHACHSAN" Class="QLKSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=COMPUTEROFLONG;Initial Catalog=QL_KHACHSAN;Integrated Security=True;Encrypt=False;Trust Server Certificate=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QL_KHACHSANConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DATPHONG" Member="DATPHONGs">
    <Type Name="DATPHONG">
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SONGUOIO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DISABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="THEODOAN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAPNHATBOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DATPHONG_PHONG_DATPHONG" Member="PHONG_DATPHONGs" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="PHONG_DATPHONG" />
      <Association Name="DATPHONG_SP_DATPHONG" Member="SP_DATPHONGs" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="SP_DATPHONG" />
      <Association Name="KHACHHANG_DATPHONG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="QL_NGUOIDUNG_DATPHONG" Member="QL_NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MANHINH" Member="DM_MANHINHs">
    <Type Name="DM_MANHINH">
      <Column Name="MAMH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MAMH" OtherKey="MAMH" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KHACHHANG_DATPHONG" Member="DATPHONGs" ThisKey="MAKH" OtherKey="MAKH" Type="DATPHONG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAIPHONG" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIPHONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SONGUOI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SOGIUONG" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG" Member="QL_NGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_DATPHONG" Member="DATPHONGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="DATPHONG" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG_NHOMNGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPHONG" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIPHONG" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MATANG" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHONG_THIETBI_PHONG" Member="THIETBI_PHONGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="THIETBI_PHONG" />
      <Association Name="PHONG_PHONG_DATPHONG" Member="PHONG_DATPHONGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG_DATPHONG" />
      <Association Name="PHONG_SP_DATPHONG" Member="SP_DATPHONGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="SP_DATPHONG" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="LOAIPHONG" IsForeignKey="true" />
      <Association Name="TANG_PHONG" Member="TANG" ThisKey="MATANG" OtherKey="MATANG" Type="TANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG_DATPHONG" Member="PHONG_DATPHONGs">
    <Type Name="PHONG_DATPHONG">
      <Column Name="MAPHONG_DATPHONG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DATPHONG_PHONG_DATPHONG" Member="DATPHONG" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="DATPHONG" IsForeignKey="true" />
      <Association Name="PHONG_PHONG_DATPHONG" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG" Member="QL_NGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_DATPHONG" Member="DATPHONGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="DATPHONG" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG_NHOMNGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG_NHOMNGUOIDUNG">
      <Column Name="MANHOMND" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOMND" OtherKey="MANHOMND" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNGs">
    <Type Name="QL_NHOMNGUOIDUNG">
      <Column Name="MANHOMND" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOMND" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="MANHOMND" OtherKey="MANHOMND" Type="QL_NGUOIDUNG_NHOMNGUOIDUNG" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MANHOMND" OtherKey="MANHOMND" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PHANQUYEN" Member="QL_PHANQUYENs">
    <Type Name="QL_PHANQUYEN">
      <Column Name="MAMH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOMND" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="DM_MANHINH" ThisKey="MAMH" OtherKey="MAMH" Type="DM_MANHINH" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOMND" OtherKey="MANHOMND" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DAXOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SANPHAM_SP_DATPHONG" Member="SP_DATPHONGs" ThisKey="MASP" OtherKey="MASP" Type="SP_DATPHONG" />
    </Type>
  </Table>
  <Table Name="dbo.SP_DATPHONG" Member="SP_DATPHONGs">
    <Type Name="SP_DATPHONG">
      <Column Name="MASPDP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DATPHONG_SP_DATPHONG" Member="DATPHONG" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="DATPHONG" IsForeignKey="true" />
      <Association Name="PHONG_SP_DATPHONG" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
      <Association Name="SANPHAM_SP_DATPHONG" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TANG" Member="TANGs">
    <Type Name="TANG">
      <Column Name="MATANG" Type="System.String" DbType="Char(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TANG_PHONG" Member="PHONGs" ThisKey="MATANG" OtherKey="MATANG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.THIETBI" Member="THIETBIs">
    <Type Name="THIETBI">
      <Column Name="MATHIETBI" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTHIETBI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="THIETBI_THIETBI_PHONG" Member="THIETBI_PHONGs" ThisKey="MATHIETBI" OtherKey="MATHIETBI" Type="THIETBI_PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.THIETBI_PHONG" Member="THIETBI_PHONGs">
    <Type Name="THIETBI_PHONG">
      <Column Name="MATHIETBI" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="PHONG_THIETBI_PHONG" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
      <Association Name="THIETBI_THIETBI_PHONG" Member="THIETBI" ThisKey="MATHIETBI" OtherKey="MATHIETBI" Type="THIETBI" IsForeignKey="true" />
    </Type>
  </Table>
</Database>