//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-J8JE5C3;Initial Catalog=QL_KHACHSAN;User ID=sa;Password=123;T" +
            "rustServerCertificate=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMPUTEROFLONG;Initial Catalog=QL_KHACHSAN;TrustServerCertificate=Tru" +
            "e")]
>>>>>>> feature/QLKH
        public string QL_KHACHSANConnectionString {
            get {
                return ((string)(this["QL_KHACHSANConnectionString"]));
            }
        }
<<<<<<< HEAD
=======
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMPUTEROFLONG;Initial Catalog=QL_KHACHSAN;Integrated Security=True;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string QL_KHACHSANConnectionString1 {
            get {
                return ((string)(this["QL_KHACHSANConnectionString1"]));
            }
        }
>>>>>>> feature/QLKH
    }
}
